version: "3"

services:
  api:
    image: imageenhancementacr.azurecr.io/imageenhancement_api
    restart: always
    expose:
      - 8050
    volumes:
        - ${WEBAPP_STORAGE_HOME}/output:/api/app/output

  ui:
    image: imageenhancementacr.azurecr.io/imageenhancement_ui
    restart: always
    ports:
      - "80:80"
    depends_on: 
      - api
    volumes:
      - ${WEBAPP_STORAGE_HOME}/output:/app/www/img/output
